---
development:
  cloud_name: dqbvgoeaj
  api_key: '441526454967413'
  api_secret: m5-n-oaKidJ8GmcRisa2-8cKGOQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dqbvgoeaj
  api_key: '441526454967413'
  api_secret: m5-n-oaKidJ8GmcRisa2-8cKGOQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dqbvgoeaj
  api_key: '441526454967413'
  api_secret: m5-n-oaKidJ8GmcRisa2-8cKGOQ
  enhance_image_tag: true
  static_image_support: false
